# Generated by Django 3.2.4 on 2021-07-06 21:12

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210706_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('startap', 'Startupper'), ('practice', 'Practitioner'), ('developer', 'Developer')], max_length=30)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
            ],
        ),
        migrations.AlterField(
            model_name='prog_level',
            name='level',
            field=models.CharField(choices=[('startap', 'Startupper'), ('practice', 'Practitioner'), ('developer', 'Developer')], max_length=20, null=True),
        ),
    ]
